### PR TITLE
Correct issues in test configuration files

### PR DESCRIPTION
**Pull request by dfcoffin**

### CODE REVIEW

**Comment by jateeter** [comment]
Don,

There is a need to document what is happening in these seed database files. In particular the use of port 8081would not be known to anyone doing a clean install run. The defaults to https in the default DC configuration seems inappropriate. 

I will pull a clean version of master and, if things do not run out of the box in STS, will suggest this commit be reversed.

jt

**Comment by jateeter** [comment]
Indeed, this commit causes the out of the box configuration of the system to fail as https, 8443 (and possibly other) attributes of the ApplicationInformation seeds are not defaulted correctly. As an addition commit (#227) has been made on top of this, there is some unwinding to do. I suspect the best solution is to make a NEW commit (#228) that corrects the problem this commit has posed.

**Comment by MartyBurns** [comment]
I will make some adjustments to the documentation to indicate how to "out of the box" test the software. The documentation in the README.md currently does not reflect the current state of the project where virtually all testing has been commented out or otherwise removed. The OpenESPI-GreenButtonCMDTest project is now the only testing for the OpenESPI suite and instructions in Common should reflect that and point to that project accordingly.

As part of this cleanup/documentation activity, I will remove all extraneous files from the ..Common/etc folder that do not relate to the OpenESPI-XXXX-java projects directly and there are a few.

Stay tuned.

**Comment by jateeter** [comment]
thx marty. As well as the out of the box test the software (and more
importantly I think) out of the box run the sw is needed. It is that
experience that is the first customer experience (i.e. no need for any of
the SoapUI stuff in that OTB experience).

jt

**Comment by dfcoffin** [comment]
Since we are not using any of the testing files, should they be deleted?

**Comment by jateeter** [comment]
Marty understands I think.

It is not that we do not use any of the test seed file configurations (we
are using them for the integration testing) - it is that the initial Out of
the Box experience is not focused on testing. It is focused on downloading,
building, and running.   1,2,3 - simple - all automatic setup if possible
(I think the ONLY thing really needed is to run one script to initialize
the databases. that script used to be "initializedatabases.sh" - I don't
know what it is now, but the contents of the default .sql files used by
initializedatabases.sh that you checked in were not correct for OTB running.

jt

**Comment by dfcoffin** [comment]
John,

Can you be more explicit with what you did to create the OTB failure?  Both Marty and I have successfully run the SoapUI Regression test script against the OTB version successfully.  It would be helpful if you can document the steps you used to create the OTB failure.

**Comment by jateeter** [comment]
I placed a new pull of the master branches from all three projects into
STS, ran "initializedatabases.sh"; from within STS, did a clean/build; run
as/run on server/; and manually when through an upload of the testdata.xml
the break occured when I was authorizing from the third party - it
redirected back to https:...8443....

It happened b/c the default seed files were incorrect.

jt

**Comment by jateeter** [comment]
or more specifically, there have been changes made within the CMDTest
project that run different script(s) than initializedatabases.sh that mask
this problem when you are doing the regression testing from there. You
didn't, I think, consider the OTB experience if one is not doing the CMD
integration testing (i.e. have not installed the SoapUI etc. test harness
infrastructure.)  It's not a requirement to have that in place just to
checkout, build, run the applications.

jt

**Comment by dfcoffin** [comment]
The SoapUI scripts rely on the fact that .initializedatabase.sh is executed during the ResetDCDB and ResettpDB steps.  To create the proper applicationInformation, authorization, subscription, and tokenstore files, individual scripts must be run to properly configure the "default" prepopulatesql_xxxxx.sql files.  Which is why the "default" prepopulatesql_xxxx.sql files were removed from the /etc files being tracked in the OpenESPI-Common-java repository.  Since the prepopulatesql_xxxx.sql were recently added back to the OpenESPI-Common-java repository by commit 7d334a0cdd564f13cbe0bf4aaa44966e9dba67ba the OpenESPI-Common-java repository is automatically updated with the latest version of the prepopulatesql_xxxx.sql files when the command "git add --all" is executed.   The default prepopulatesql_xxxx.sql files were removed from the OpenESPI-Common-java repository to ensure users would properly initialize them.

**Comment by MartyBurns** [comment]
I said I would address the comments. How about give time to do it :-)

**Comment by jateeter** [comment]
1+ on that!

**Pull request merged**
